### ISSUE TITLE
Error in extract_features_from_bureau module

### ISSUE THREAD

**Issue by ETM1123** [DSEI21000-S21/project-home-credit#4]
NameError: name 'data' is not defined

Please fix this in the data_extract_utils script. There's a call of the data without of it being defined. Perhaps you can pass it as a parameter then we can define it in our own code. For example: 

extract_features_from_bureau(bureau_df, bureau_balances_df, data)

**Comment by Amauris** [comment]
Good, find must have been an error when I move the logic from experiment notebook to function. Should be fixed now.,
