### ISSUE TITLE
Odd result after joining the bureau and bureau_balance table

### ISSUE THREAD

**Issue by ETM1123** [DSEI21000-S21/project-home-credit#5]
I don't think this is an error ... at least code wise - after joining the two tables using the provided function, the number of instances in the joined table is approximately five times the training and testing data combined. This implies that there are very few SK_ID_CURR ids (i.e applicants for training and testing data) that corresponds to the joined tables...

This seems wrong; however, based on my observation, I see no logical error in the code. I don't know what this means - this is a possible error. Please confirm result.

**Comment by Amauris** [comment]
Ah this is expected. A SK_ID_CURR represents an applicant, and an applicant will have multiple loan records SK_ID_BUREAU (1 to many relationship).
I guess we will have to do some further aggregation on SK_ID_CURR for the merged bureau_data. I'll try working on doing so
