### ISSUE TITLE
OPTIMIZE extract_features_from_bureau .. 10MINS TO EXECUTE 

### ISSUE THREAD

**Issue by ETM1123** [DSEI21000-S21/project-home-credit#6]
I investigated this function a bit - line 32 
dpd_counts_df = bureau_balances_df.groupby(['SK_ID_BUREAU']).apply(sum_of_dpd)

is the line that takes the longest to execute!!!

**Comment by Amauris** [comment]
I noticed this, currently investigating a more effficient form. If non exists than maybe we can just store post processing csv in drop box

**Comment by Amauris** [comment]
Should be much faster after [commit](https://github.com/DSEI21000-S21/project-home-credit/commit/a9e6a0698ff29e1c59924aa773748b103ef61a7e#diff-3122c0d8e082e7df7b259240f857733920f189958ca8e9c7c2c38f8aa579ec16)
